### ISSUE TITLE
trakt import

### ISSUE THREAD

**Issue by psyciknz** [leepeuker/movary#172]
Looking at the readme it say Trakt user Id and client Id (not secret, for the oath token).  I already had one for oauth, and after trying all items, the pin, secret and id (pin and secret got 403 errors), ID gets:
```
david@drogo:/hdd/docker-data/media$  (master)$ docker exec -it movary php bin/console.php trakt:import --userId=1 --history --overwrite
2022-12-21 20:31:37:966315 - Importing history...
2022-12-21 20:31:39:147670 - ERROR: Could not complete trakt import.
[2022-12-21T20:31:39.148093+00:00] movary.ERROR: Could not complete trakt import. {"exception":"[object] (TypeError(code: 0): Movary\\Api\\Trakt\\ValueObject\\TraktMovie::__construct(): Argument #4 ($imdbId) must be of type string, null given, called in /app/src/Api/Trakt/ValueObject/TraktMovie.php on line 25 at /app/src/Api/Trakt/ValueObject/TraktMovie.php:9)"} []
```

I then tried a new credential on trakt with no oauth, but I got the same error.

I assume my command is correct, it's taken from readme, and there is only one userid.

Sorry for the flurry of issues.  But keen to see this working after trakt's api/db issues.

**Comment by psyciknz** [comment]
Running history import via ui gets the following log entrys
```
2022-12-21 20:34:35:473018 - Processing job...
PHP Fatal error:  Uncaught TypeError: Movary\Api\Trakt\ValueObject\TraktMovie::__construct(): Argument #4 ($imdbId) must be of type string, null given, called in /app/src/Api/Trakt/ValueObject/TraktMovie.php on line 25 and defined in /app/src/Api/Trakt/ValueObject/TraktMovie.php:9
Stack trace:
#0 /app/src/Api/Trakt/ValueObject/TraktMovie.php(25): Movary\Api\Trakt\ValueObject\TraktMovie->__construct('Dutch Influence', Object(Movary\ValueObject\Year), Object(Movary\Api\Trakt\ValueObject\TraktId), NULL, 220442)
#1 /app/src/Api/Trakt/ValueObject/User/Movie/Watched/Dto.php(21): Movary\Api\Trakt\ValueObject\TraktMovie::createFromArray(Array)
#2 /app/src/Api/Trakt/ValueObject/User/Movie/Watched/DtoList.php(25): Movary\Api\Trakt\ValueObject\User\Movie\Watched\Dto::createFromArray(Array)
#3 /app/src/Api/Trakt/TraktApi.php(40): Movary\Api\Trakt\ValueObject\User\Movie\Watched\DtoList::createFromArray(Array)
#4 /app/src/Service/Trakt/ImportWatchedMovies.php(44): Movary\Api\Trakt\TraktApi->fetchUserMoviesWatched('87959db8f529580...', 'coleadve')
#5 /app/src/Service/Trakt/ImportWatchedMovies.php(80): Movary\Service\Trakt\ImportWatchedMovies->execute(1)
#6 /app/src/Service/JobProcessor.php(32): Movary\Service\Trakt\ImportWatchedMovies->executeJob(Object(Movary\ValueObject\Job))
#7 /app/src/Command/ProcessJobs.php(84): Movary\Service\JobProcessor->processJob(Object(Movary\ValueObject\Job))
#8 /app/src/Command/ProcessJobs.php(47): Movary\Command\ProcessJobs->processJob()
#9 /app/vendor/symfony/console/Command/Command.php(312): Movary\Command\ProcessJobs->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Movary\Command\ProcessJobs), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/bin/console.php(22): Symfony\Component\Console\Application->run()
#14 {main}
  thrown in /app/src/Api/Trakt/ValueObject/TraktMovie.php on line 9
```

If that's more useful

**Comment by leepeuker** [comment]
Thank you very much for reporting your issue and for the extend log information.

It seems like I only imported movies from trakt yet which had an imdb id set, your movie `Dutch Influence` does not have one. This should be no problem because the imdb id from trakt is not really used anywhere, so I just removed that part of the code. Please try the new version 0.35.1, the error should be gone.

**Comment by psyciknz** [comment]
Cool will do.

Do you intend movary at some point to do the same with tv shows/episodes?    Or is that a whole 'nother kettle of fish?

**Comment by leepeuker** [comment]
There are no plans for supporting tv shows currently, sorry. I want to solely focus on movies to make this part as good as possible.

**Comment by psyciknz** [comment]
Ok thanks. I was hoping to have a one stop shop 

And doubt I could hack around in php to add it.
