### ISSUE TITLE
Unexpected server error when editing the general date format

### ISSUE THREAD

**Issue by JVT038** [leepeuker/movary#364]
When editing the date in the settings -> account -> general, the user sees 'Unexpected server error' and this error will appear in the logs:

```
[2023-05-21T22:03:35.323221+02:00] movary.EMERGENCY: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'watchlist_automatic_removal_enabled' at row 1 {"exception":"[object] (Doctrine\\DBAL\\Exception\\DriverException(code: 1366): An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'watchlist_automatic_removal_enabled' at row 1 at C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Driver\\API\\MySQL\\ExceptionConverter.php:117)
[stacktrace]
#0 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(1931): Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter->convert()
#1 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(1874): Doctrine\\DBAL\\Connection->handleDriverException()
#2 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(1202): Doctrine\\DBAL\\Connection->convertExceptionDuringQuery()
#3 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(770): Doctrine\\DBAL\\Connection->executeStatement()
#4 C:\\path\\to\\movary\\src\\Domain\\User\\UserRepository.php(534): Doctrine\\DBAL\\Connection->update()
#5 C:\\path\\to\\movary\\src\\Domain\\User\\UserApi.php(274): Movary\\Domain\\User\\UserRepository->updateWatchlistAutomaticRemovalEnabled()
#6 C:\\path\\to\\movary\\src\\HttpController\\SettingsController.php(478): Movary\\Domain\\User\\UserApi->updateWatchlistAutomaticRemovalEnabled()
#7 [internal function]: Movary\\HttpController\\SettingsController->updateGeneral()
#8 C:\\path\\to\\movary\\vendor\\php-di\\invoker\\src\\Invoker.php(74): call_user_func_array()
#9 C:\\path\\to\\movary\\vendor\\php-di\\php-di\\src\\Container.php(248): Invoker\\Invoker->call()
#10 C:\\path\\to\\movary\\public\\index.php(38): DI\\Container->call()
#11 {main}

[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1366): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'watchlist_automatic_removal_enabled' at row 1 at C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Exception.php:28)
[stacktrace]
#0 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Statement.php(123): Doctrine\\DBAL\\Driver\\PDO\\Exception::new()
#1 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(1196): Doctrine\\DBAL\\Driver\\PDO\\Statement->execute()
#2 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(770): Doctrine\\DBAL\\Connection->executeStatement()
#3 C:\\path\\to\\movary\\src\\Domain\\User\\UserRepository.php(534): Doctrine\\DBAL\\Connection->update()
#4 C:\\path\\to\\movary\\src\\Domain\\User\\UserApi.php(274): Movary\\Domain\\User\\UserRepository->updateWatchlistAutomaticRemovalEnabled()
#5 C:\\path\\to\\movary\\src\\HttpController\\SettingsController.php(478): Movary\\Domain\\User\\UserApi->updateWatchlistAutomaticRemovalEnabled()
#6 [internal function]: Movary\\HttpController\\SettingsController->updateGeneral()
#7 C:\\path\\to\\movary\\vendor\\php-di\\invoker\\src\\Invoker.php(74): call_user_func_array()
#8 C:\\path\\to\\movary\\vendor\\php-di\\php-di\\src\\Container.php(248): Invoker\\Invoker->call()
#9 C:\\path\\to\\movary\\public\\index.php(38): DI\\Container->call()
#10 {main}

[previous exception] [object] (PDOException(code: HY000): SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'watchlist_automatic_removal_enabled' at row 1 at C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Statement.php:121)
[stacktrace]
#0 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Driver\\PDO\\Statement.php(121): PDOStatement->execute()
#1 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(1196): Doctrine\\DBAL\\Driver\\PDO\\Statement->execute()
#2 C:\\path\\to\\movary\\vendor\\doctrine\\dbal\\src\\Connection.php(770): Doctrine\\DBAL\\Connection->executeStatement()
#3 C:\\path\\to\\movary\\src\\Domain\\User\\UserRepository.php(534): Doctrine\\DBAL\\Connection->update()
#4 C:\\path\\to\\movary\\src\\Domain\\User\\UserApi.php(274): Movary\\Domain\\User\\UserRepository->updateWatchlistAutomaticRemovalEnabled()
#5 C:\\path\\to\\movary\\src\\HttpController\\SettingsController.php(478): Movary\\Domain\\User\\UserApi->updateWatchlistAutomaticRemovalEnabled()
#6 [internal function]: Movary\\HttpController\\SettingsController->updateGeneral()
#7 C:\\path\\to\\movary\\vendor\\php-di\\invoker\\src\\Invoker.php(74): call_user_func_array()
#8 C:\\path\\to\\movary\\vendor\\php-di\\php-di\\src\\Container.php(248): Invoker\\Invoker->call()
#9 C:\\path\\to\\movary\\public\\index.php(38): DI\\Container->call()
#10 {main}
"} []
```

It has probably something to do with the column `watchlist_automatic_removal_enabled`

**Comment by leepeuker** [comment]
Fixed in https://github.com/leepeuker/movary/pull/366
