### ISSUE TITLE
Hide Actor / Actress from dashboard

### ISSUE THREAD

**Issue by sahinakkaya** [leepeuker/movary#505]
### Description

I have an interesting watch history such that an actor named "Joseph Oliveira" comes up as one of my most watched actors. He doesn't have any image and you probably don't know about him.

<img width="1311" alt="resim" src="https://github.com/leepeuker/movary/assets/32161460/fc92890e-af2d-4f62-9e90-1a52072bef07">

Here are the films that he was in: 
<img width="1327" alt="resim" src="https://github.com/leepeuker/movary/assets/32161460/ec7bd1a2-bb93-49eb-84ee-78ff463f452d">

When I see the movie list, I thought this was a bug because there is no way someone played in all these movies and I didn't notice. Well, it wasn't a bug. Stats are correct. Apparently, our guy didn't play exciting roles. He was bartender, officer, agent etc. 

While I appreciate his work, I don't think he deserves a place next to the literally top guys. sorry if you are reading, Joseph :(

### Desired Behavior

It would be nice if we could hide actors / actresses.

**Comment by leepeuker** [comment]
Ah yes very good suggestion, I had this problem too with Stan Lee. With all his Marvel cameos he was in my top actors and my solution at the time was to hard code that Stan Lee is ignored (see [here](https://github.com/leepeuker/movary/blob/8b0a2d8fcfbb22af38ab6c58f61c1af9f0ca0183/src/Domain/Movie/MovieRepository.php#L95) :D). So I definitely agree there should be an easy way to exclude people from lists like this.

**Comment by leepeuker** [comment]
Done in https://github.com/leepeuker/movary/issues/524

You can no hide persons from top lists:
![image](https://github.com/leepeuker/movary/assets/19872901/5f1aa822-4bd2-4821-ba7d-9c8736eb523d)

@sahinakkaya You can use the nightly image to test this or wait for the next release :)

**Comment by sahinakkaya** [comment]
@leepeuker I wanted to try nightly release but migrations failed. Here are the steps I followed and their output:
```
sahin@sahinakkaya ~/movary> docker pull leepeuker/movary:nightly
nightly: Pulling from leepeuker/movary
96526aa774ef: Pull complete
c2b4f1479ad8: Pull complete
e266ff8d3cec: Pull complete
6127d1435a8c: Pull complete
3cd239193044: Pull complete
e382ad9012a8: Pull complete
4d8d49898a73: Pull complete
d4492a3b5df6: Pull complete
194b7a99c342: Pull complete
b9c5b8064206: Pull complete
e29e25f92fa7: Pull complete
b5ede5b04095: Pull complete
58a1e22cf0fc: Pull complete
3174979ed54f: Pull complete
e776f3cbdcf6: Pull complete
5699fbeb09aa: Pull complete
bb611381e661: Pull complete
d9b65e093ebc: Pull complete
c50078af349f: Pull complete
3ca9035d876e: Pull complete
4f4fb700ef54: Pull complete
e386af74a5b7: Pull complete
1de90efba8db: Pull complete
792de9a61f62: Pull complete
e2a409cf028e: Pull complete
0ce931e94989: Pull complete
Digest: sha256:cd3dc0262485ab1afb8495eef102069c10cf12fd033053bcc04d972fbfd29f60
Status: Downloaded newer image for leepeuker/movary:nightly
docker.io/leepeuker/movary:nightly

sahin@sahinakkaya ~/movary> docker compose down && docker compose up -d
[+] Running 3/3
 ✔ Container movary          Removed                                                                                                             5.9s
 ✔ Container movary-mysql-1  Removed                                                                                                             5.9s
 ✔ Network movary_default    Removed                                                                                                             0.1s
[+] Building 0.0s (0/0)
[+] Running 3/3
 ✔ Network movary_default    Created                                                                                                             0.1s
 ✔ Container movary-mysql-1  Started                                                                                                             1.1s
 ✔ Container movary          Started                                                                                                             1.1s

sahin@sahinakkaya ~/movary> docker exec movary php bin/console.php database:migration:migrate
PHP Deprecated:  Optional parameter $searchTerm declared before required parameter $personFilterUserId is implicitly treated as a required parameter in /app/src/Domain/Movie/MovieRepository.php on line 272
PHP Deprecated:  Optional parameter $gender declared before required parameter $personFilterUserId is implicitly treated as a required parameter in /app/src/Domain/Movie/MovieRepository.php on line 272
using config file settings/phinx.php
using config parser php
using migration paths
 - /app/db/migrations/mysql
warning no environment specified, defaulting to: dynamic
using adapter mysql
using database movary
ordering by creation time
InvalidArgumentException: Could not find class "AddIsHiddenInTopListsToPersonTable" in file "/app/settings/../db/migrations/mysql/20231006174123_AddIsHiddenInTopListsToPersonTable.php" in /app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php:813
Stack trace:
#0 /app/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(313): Phinx\Migration\Manager->getMigrations('dynamic')
#1 /app/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate('dynamic', NULL, false)
#2 /app/vendor/symfony/console/Command/Command.php(312): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/src/Command/DatabaseMigrationMigrate.php(36): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Command/Command.php(312): Movary\Command\DatabaseMigrationMigrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(Movary\Command\DatabaseMigrationMigrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /app/bin/console.php(33): Symfony\Component\Console\Application->run()
#9 {main}
```

**Comment by leepeuker** [comment]
@sahinakkaya Oh yes, sorry my bad, I fucked up the migration file name. Please pull the latest nightly image again, it should work now

**Comment by sahinakkaya** [comment]
Yeah, it works now. Thank you for your efforts!
